### ISSUE TITLE
Restructure README

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#1330]
## 📚 Documentation

- [x] Update README structure #1329
- [x] Tune README header #1329
- [x] Add content of about, demos, features sections #1329
- [x] Add Aim overview illustrations #1329
- [x] Tune getting started and integrations sections #1329
- [x] Tune demos sections #1329
- [x] Add screenshot or gif to the header #1329
- [x] Optimize images #1353
- [x] Update high-level roadmap #1363
