### ISSUE TITLE
Improve documentation after restructuring

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#1365]
## 📚 Documentation

The new structure of docs has clean structure and organized in a way to make it easy to get useful information regardless how deep is your knowledge of Aim.
However, certain areas can be improved further. Here is the list of what can be improved (feel free to add more items)

### TODO
- [ ] `understanding/overview.md` Put a components diagram at the bottom of the page.
- [ ]  `understanding/data_storage.md` Add data flow diagram (from tracking to UI).
- [ ]  Add `Glossary` section.
- [ ] Tune cross-links
- [ ] Add `Archive runs` in manage runs page
- [ ] Document querying of all media and object
- [ ] Document system resource usage and runs other attributes in `configuring runs` section
- [x] Document Aim UI concepts and guides
