### ISSUE TITLE
Log images and masks

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#332]
Aim does not log images or other artifacts alike.

For a lot of Reinforcement Learning and Computer Vision use-cases, there is a need to track images, masks and display them along with the metrics and other insights.

**TODO:** Finalize high-level user-perspective details of this feature

**Comment by LarsHill** [comment]
For NLP researchers being able to log plain text (similar to what TensorBoard offers) would be great, too.

For example, logging a few generated sentences per Epoch while training a text generation model.

Since it is quite related to logging images and other artefacts (see TensorBoard API) I didn't create a new issue.

**Comment by VkoHov** [comment]
- [ ] Implement images explore step and index range and interval functionality. resolves #[856](https://github.com/aimhubio/aim/pull/856)
- [ ] Implement the lazy loading of images based on their occurrence in the viewport. resolves #[938](https://github.com/aimhubio/aim/pull/938)
- [ ] New App for exploring logged images.

**Comment by gorarakelyan** [comment]
Images tracking and visualization is available from Aim v3.1.0. Segmentation masks will be added as an enhancement in the later versions. Will open a separate issue for that.
